# Generated by Django 4.2.4 on 2023-08-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="key_skills",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
