# Generated by Django 4.2.4 on 2023-08-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_job_required_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="shortlisted",
            field=models.BooleanField(default=True),
        ),
    ]
