# Generated by Django 4.2.4 on 2023-08-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_remove_job_shortlisted"),
    ]

    operations = [
        migrations.AddField(
            model_name="applyjob",
            name="shortlisted",
            field=models.BooleanField(default=False),
        ),
    ]
