# Generated by Django 4.2.4 on 2023-08-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0008_city_alter_job_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="city",
            field=models.CharField(max_length=100),
        ),
    ]
